# Generated by Django 5.2.10 on 2026-01-25 03:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_anonyme', models.CharField(help_text="ID pour l'IA", max_length=50, unique=True)),
                ('nom_complet', models.CharField(max_length=150)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('service', models.CharField(choices=[('ADMIN', 'Administration / Accueil'), ('MEDECIN', 'Consultation / Médecine'), ('RADIO', 'Radiologie / IA')], default='ADMIN', max_length=10)),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Biomarqueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_examen', models.DateField(auto_now_add=True)),
                ('taux_CEA', models.FloatField(verbose_name='Antigène Carcino-Embryonnaire (ng/mL)')),
                ('taux_CYFRA21', models.FloatField(verbose_name='CYFRA 21-1 (ng/mL)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomarqueurs', to='administration.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilClinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabac_score', models.IntegerField(default=0, help_text='Paquets/Année')),
                ('exposition_toxique', models.BooleanField(default=False)),
                ('antecedents_familiaux', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='administration.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ScannerCT',
            fields=[
                ('id_scan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_dicom', models.FileField(upload_to='scanners/%Y/%m/%d/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='administration.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_malignite', models.FloatField(blank=True, null=True)),
                ('details_nodules', models.JSONField(blank=True, null=True)),
                ('avis_medecin', models.TextField(blank=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='administration.scannerct')),
            ],
        ),
    ]
