# Generated by Django 5.2.10 on 2026-02-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_analyseia_date_analyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseia',
            name='consulte_par_medecin',
            field=models.BooleanField(default=False),
        ),
    ]
