# Generated by Django 5.2.10 on 2026-01-30 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_analyseia_date_analyse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateTimeField()),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PREVU', 'Prévu'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PREVU', max_length=10)),
                ('notes_medicales', models.TextField(blank=True, null=True)),
                ('medecin', models.ForeignKey(limit_choices_to={'service': 'MEDECIN'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='administration.patient')),
            ],
        ),
    ]
